# Generated by Django 5.0.6 on 2024-06-26 13:54

import database.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'attribute',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=60)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], max_length=20, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='dob must be in the format: dd/mm/yyyy', regex='^[0-9]{1,2}\\/[0-9]{1,2}\\/[0-9]{4}$')])),
                ('phoneno', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the 10 digit format: '9999999999'", regex='^(\\d{10})$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHeaderDetail',
            fields=[
                ('purchase_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('purchased_date', models.DateTimeField(auto_now_add=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'purchase_header_detail',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=60)),
                ('phoneno', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the 10 digit format: '9999999999'", regex='^(\\d{10})$')])),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('has_variants', models.BooleanField(default=False)),
                ('brand_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.brand')),
                ('category_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('product_attr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attribute_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.attribute')),
                ('product_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.product')),
            ],
            options={
                'db_table': 'product_attribute',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('product_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('product_image', models.ImageField(blank=True, default=None, null=True, upload_to='product_images')),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('product_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.product')),
            ],
            options={
                'db_table': 'product_detail',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('product_price_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product_detail_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.productdetail')),
            ],
            options={
                'db_table': 'product_price',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('variant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('variant_name', models.CharField(max_length=100, null=True)),
                ('product_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.product')),
            ],
            options={
                'db_table': 'product_variant',
            },
        ),
        migrations.AddField(
            model_name='productdetail',
            name='variant_ref',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.productvariant'),
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('purchase_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_detail_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.productdetail')),
                ('purchase_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.purchaseheaderdetail')),
            ],
            options={
                'db_table': 'purchase_item',
            },
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('purchase_payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.purchaseheaderdetail')),
            ],
            options={
                'db_table': 'purchase_payment',
            },
        ),
        migrations.CreateModel(
            name='SaleHeaderDetail',
            fields=[
                ('sale_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sold_date', models.DateTimeField(auto_now_add=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('customer_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.customer')),
            ],
            options={
                'db_table': 'sale_header_detail',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('sale_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_with_price_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.productprice')),
                ('sale_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.saleheaderdetail')),
            ],
            options={
                'db_table': 'sale_item',
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('sale_payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.saleheaderdetail')),
            ],
            options={
                'db_table': 'sale_payment',
            },
        ),
        migrations.AddField(
            model_name='purchaseheaderdetail',
            name='supplier_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.supplier'),
        ),
        migrations.CreateModel(
            name='VariantAttributeValue',
            fields=[
                ('variant_attr_value_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=60)),
                ('product_attr_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.productattribute')),
                ('variant_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.productvariant')),
            ],
            options={
                'db_table': 'variant_attribute_value',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=60)),
                ('location', models.TextField(blank=True, max_length=200, null=True)),
                ('incharge_person', models.ForeignKey(default=database.models.get_default_user, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('stock_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product_with_price_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.productprice')),
                ('warehouse_ref', models.ForeignKey(default=database.models.get_warehouse_default, on_delete=django.db.models.deletion.SET_DEFAULT, to='database.warehouse')),
            ],
            options={
                'db_table': 'stock_detail',
            },
        ),
    ]
