# Generated by Django 5.0.6 on 2024-06-28 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='product_detail_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.productdetail'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product_with_price_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.productprice'),
        ),
    ]
