# Generated by Django 5.0.6 on 2024-07-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_stockdetail_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetail',
            options={'ordering': ['product_ref']},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ['product_detail_ref']},
        ),
        migrations.AddField(
            model_name='customer',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='low_stock_threshold',
            field=models.IntegerField(default=5),
        ),
    ]
