# Generated by Django 5.0.6 on 2024-07-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_productdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(default='variant', max_length=100),
            preserve_default=False,
        ),
    ]
