# Generated by Django 5.0.6 on 2024-06-18 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, help_text='dob format: dd/mm/yyyy', null=True, validators=[django.core.validators.RegexValidator(message='dob must be in the format: dd/mm/yyyy', regex='/^[0-9]{1,2}\\/[0-9]{1,2}\\/[0-9]{4}$/')]),
        ),
    ]
