# Generated by Django 5.0.6 on 2024-06-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='created_date',
            new_name='added_date',
        ),
    ]
