# Generated by Django 5.0.6 on 2024-06-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_purchaseitem_product_detail_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetail',
            name='status',
            field=models.CharField(choices=[('good', 'Good'), ('missed', 'Missed'), ('damaged', 'Damaged')], default='good', max_length=20),
        ),
    ]
