# Generated by Django 5.0.6 on 2024-05-29 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_variantattributes_attribute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderheader',
            old_name='purchase_id',
            new_name='purch_header_id',
        ),
        migrations.RenameField(
            model_name='purchaseorderline',
            old_name='purchase_detail_id',
            new_name='purch_order_line_id',
        ),
        migrations.RenameField(
            model_name='saleorderheader',
            old_name='sale_id',
            new_name='sale_header_id',
        ),
        migrations.RenameField(
            model_name='saleorderline',
            old_name='sale_detail_id',
            new_name='sale_order_line_id',
        ),
        migrations.RenameField(
            model_name='variantattributevalue',
            old_name='variant_attr_value_id',
            new_name='var_attr_value_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.category'),
        ),
    ]
