# Generated by Django 5.0.6 on 2024-06-18 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_customer_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='dob must be in the format: dd/mm/yyyy', regex='/^[0-9]{1,2}\\/[0-9]{1,2}\\/[0-9]{4}$/')]),
        ),
    ]
