# Generated by Django 5.0.6 on 2024-05-30 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rename_purchase_id_purchaseorderheader_purch_header_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseOrderLine',
            new_name='PurchaseItem',
        ),
        migrations.RenameModel(
            old_name='SaleOrderPayment',
            new_name='PurchasePayment',
        ),
        migrations.RenameModel(
            old_name='SaleOrderLine',
            new_name='SaleItem',
        ),
        migrations.RenameModel(
            old_name='PurchaseOrderPayment',
            new_name='SalePayment',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='purch_order_line_id',
            new_name='purchase_item_id',
        ),
        migrations.RenameField(
            model_name='purchaseorderheader',
            old_name='purch_header_id',
            new_name='purchase_id',
        ),
        migrations.RenameField(
            model_name='purchasepayment',
            old_name='sale_payment_id',
            new_name='purchase_payment_id',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='sale_order_line_id',
            new_name='sale_item_id',
        ),
        migrations.RenameField(
            model_name='saleorderheader',
            old_name='sale_header_id',
            new_name='sale_id',
        ),
        migrations.RenameField(
            model_name='salepayment',
            old_name='purchase_payment_id',
            new_name='sale_payment_id',
        ),
        migrations.RemoveField(
            model_name='purchasepayment',
            name='sale_ref',
        ),
        migrations.RemoveField(
            model_name='salepayment',
            name='purchase_ref',
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='purchase_ref',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.purchaseorderheader'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salepayment',
            name='sale_ref',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.saleorderheader'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='purchaseitem',
            table='purchase_item',
        ),
        migrations.AlterModelTable(
            name='purchasepayment',
            table='purchase_payment',
        ),
        migrations.AlterModelTable(
            name='saleitem',
            table='sale_item',
        ),
        migrations.AlterModelTable(
            name='salepayment',
            table='sale_payment',
        ),
    ]
