# Generated by Django 5.0.6 on 2024-05-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_rename_purchaseorderline_purchaseitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product_images'),
        ),
    ]
