# Generated by Django 5.0.6 on 2024-06-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_productprice_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='cost_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='selling_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseheaderdetail',
            name='bill_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_cost_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='balance_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='paid_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='saleheaderdetail',
            name='bill_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='saleheaderdetail',
            name='discount_amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='saleheaderdetail',
            name='discount_percent',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_sell_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='balance_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='paid_amount',
            field=models.FloatField(),
        ),
    ]
