# Generated by Django 5.0.6 on 2024-06-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_productdetail_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseOrderHeader',
            new_name='PurchaseHeaderDetail',
        ),
        migrations.RenameModel(
            old_name='SaleOrderHeader',
            new_name='SaleHeaderDetail',
        ),
    ]
