# Generated by Django 5.0.6 on 2024-06-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_productprice_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
