# Generated by Django 5.0.6 on 2024-06-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_rename_purchaseorderheader_purchaseheaderdetail_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchaseheaderdetail',
            table='purchase_header_detail',
        ),
        migrations.AlterModelTable(
            name='saleheaderdetail',
            table='sale_header_detail',
        ),
    ]
