# Generated by Django 5.0.6 on 2024-06-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_customer_created_date_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleheaderdetail',
            name='discount_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='saleheaderdetail',
            name='discount_percent',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
